=== openbmc/phosphor-modbus/rtu/schemas/device_profile.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ModbusRTUDeviceProfile",
    "type": "object",
    "required": [
        "DeviceType",
        "DeviceModel",
        "Parity",
        "BaudRate",
        "ProbeRegister"
    ],
    "additionalProperties": false,
    "properties": {
        "DeviceType": {
            "type": "string",
            "enum": [
                "BatteryBackupUnit",
                "CapacitorBankUnit",
                "FlowMeter",
                "HeatExchanger",
                "PowerMonitorModule",
                "PowerShelf",
                "PowerSupplyUnit",
                "ReservoirPumpUnit",
                "Valve"
            ]
        },
        "DeviceModel": {
            "type": "string",
            "enum": [
                "Artesyn7000552480000",
                "Artesyn7000552531000",
                "Artesyn7000555240000",
                "BelimoEV200ARXE",
                "Danfoss003Z8540",
                "DeltaBBUBC100AE000",
                "DeltaBBUBS723AE000",
                "DeltaBBUBU123AE000",
                "DeltaECD17020037",
                "DeltaECD27010006",
                "DeltaECD68000047",
                "DeltaECD68000049",
                "DeltaECD70000017",
                "DeltaECD70000020",
                "DeltaRDF040DSS5193E0",
                "PanasonicBJA3C0002A",
                "PanasonicBJBPM103A",
                "PanasonicBJBSB103A"
            ]
        },
        "Parity": {
            "type": "string",
            "enum": ["None", "Even", "Odd"]
        },
        "BaudRate": {
            "type": "integer"
        },
        "ProbeRegister": {
            "type": "object",
            "required": ["Offset", "Size", "ExpectedValue"],
            "additionalProperties": false,
            "properties": {
                "Offset": { "type": "string", "pattern": "^0x[0-9A-Fa-f]+$" },
                "Size": { "type": "integer" },
                "ExpectedValue": {
                    "oneOf": [{ "type": "integer" }, { "type": "string" }]
                }
            }
        },
        "InventoryRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Type": {
                        "type": "string",
                        "enum": [
                            "BuildDate",
                            "Manufacturer",
                            "Model",
                            "PartNumber",
                            "SerialNumber",
                            "SparePartNumber"
                        ]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Format": {
                        "type": "string",
                        "enum": ["String", "Integer"],
                        "default": "String"
                    }
                }
            }
        },
        "SensorRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size", "Format"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": [
                            "FanTach",
                            "LiquidFlow",
                            "Power",
                            "Pressure",
                            "Temperature",
                            "Voltage",
                            "Current",
                            "Airflow",
                            "Altitude",
                            "Energy",
                            "Frequency",
                            "Humidity",
                            "Utilization",
                            "Valve",
                            "Charge",
                            "RotationalPosition"
                        ]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Precision": { "type": "integer", "default": 0 },
                    "Scale": { "type": "number", "default": 1.0 },
                    "Shift": { "type": "number", "default": 0.0 },
                    "IsSigned": { "type": "boolean", "default": false },
                    "Format": {
                        "type": "string",
                        "enum": ["FixedPoint", "Float32", "Integer"]
                    }
                },
                "if": {
                    "properties": { "Format": { "const": "Float32" } }
                },
                "then": {
                    "properties": { "Size": { "const": 2 } }
                }
            }
        },
        "StatusRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Offset", "Bits"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Bits": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "Type",
                                "BitPosition",
                                "Value"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "Name": { "type": "string" },
                                "Type": {
                                    "type": "string",
                                    "enum": [
                                        "ControllerFailure",
                                        "FanFailure",
                                        "FilterFailure",
                                        "PowerFault",
                                        "PumpFailure",
                                        "LeakDetectedCritical",
                                        "LeakDetectedWarning",
                                        "SensorFailure",
                                        "SensorReadingCritical",
                                        "SensorReadingWarning"
                                    ]
                                },
                                "BitPosition": { "type": "integer" },
                                "Value": { "type": "boolean" }
                            }
                        }
                    }
                }
            }
        },
        "MetricRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size", "Format"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["ValveClosedDuration", "ValveOpenDuration"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Precision": { "type": "integer", "default": 0 },
                    "Scale": { "type": "number", "default": 1.0 },
                    "Shift": { "type": "number", "default": 0.0 },
                    "IsSigned": { "type": "boolean", "default": false },
                    "Format": {
                        "type": "string",
                        "enum": ["FixedPoint", "Float32", "Integer"]
                    }
                },
                "if": {
                    "properties": { "Format": { "const": "Float32" } }
                },
                "then": {
                    "properties": { "Size": { "const": 2 } }
                }
            }
        },
        "FirmwareRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["Version", "Update"]
                    },
                    "Format": {
                        "type": "string",
                        "enum": ["String", "Integer"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" }
                }
            }
        },
        "ConfigRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["UnixTime"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Period": { "type": "integer" }
                }
            }
        }
    }
}

=== openbmc/phosphor-modbus/rtu/profiles/DeltaBBUBC100AE000PowerMonitorModule.json
{
    "DeviceType": "PowerMonitorModule",
    "DeviceModel": "DeltaBBUBC100AE000",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x8",
        "Size": 8,
        "ExpectedValue": "Delta"
    },
    "InventoryRegisters": [
        {
            "Type": "SparePartNumber",
            "Offset": "0x0",
            "Size": 8
        },
        {
            "Type": "Manufacturer",
            "Offset": "0x8",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x10",
            "Size": 8
        },
        {
            "Type": "BuildDate",
            "Offset": "0x18",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x20",
            "Size": 16
        }
    ],
    "FirmwareRegisters": [
        {
            "Name": "PMM_FW_Revision",
            "Type": "Version",
            "Offset": "0x38",
            "Size": 4
        }
    ],
    "SensorRegisters": [],
    "StatusRegisters": [
        {
            "Name": "GEN_ALARM",
            "Offset": "0x59",
            "Bits": [
                {
                    "Name": "MISSING_MODULES",
                    "Type": "ControllerFailure",
                    "BitPosition": 0,
                    "Value": true
                },
                {
                    "Name": "SHELF_EEPROM_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 1,
                    "Value": true
                },
                {
                    "Name": "MODULE_MODBUS_COMM_ERR",
                    "Type": "ControllerFailure",
                    "BitPosition": 4,
                    "Value": true
                },
                {
                    "Name": "PMM_MODBUS_COMM_ERR",
                    "Type": "ControllerFailure",
                    "BitPosition": 5,
                    "Value": true
                },
                {
                    "Name": "SERIAL_LINK_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 6,
                    "Value": true
                },
                {
                    "Name": "MODULE_ALERTS",
                    "Type": "ControllerFailure",
                    "BitPosition": 8,
                    "Value": true
                },
                {
                    "Name": "BB_OVER_TEMP_WARN",
                    "Type": "SensorReadingWarning",
                    "BitPosition": 9,
                    "Value": true
                },
                {
                    "Name": "BB_OVER_TEMP_ALARM",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 10,
                    "Value": true
                },
                {
                    "Name": "ISHARE_CABLE_NOT_DETECTED",
                    "Type": "ControllerFailure",
                    "BitPosition": 12,
                    "Value": true
                }
            ]
        },
        {
            "Name": "COMM_ALARM",
            "Offset": "0x5D",
            "Bits": [
                {
                    "Name": "RX_SERIAL_INPUT_FAILURE",
                    "Type": "ControllerFailure",
                    "BitPosition": 0,
                    "Value": true
                },
                {
                    "Name": "MODULE1_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 1,
                    "Value": true
                },
                {
                    "Name": "MODULE2_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "MODULE3_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 3,
                    "Value": true
                },
                {
                    "Name": "MODULE4_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 4,
                    "Value": true
                },
                {
                    "Name": "MODULE5_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 5,
                    "Value": true
                },
                {
                    "Name": "MODULE6_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 6,
                    "Value": true
                },
                {
                    "Name": "SHELF_EEPROM_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 8,
                    "Value": true
                },
                {
                    "Name": "MODULE7_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 9,
                    "Value": true
                },
                {
                    "Name": "MODULE8_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 10,
                    "Value": true
                },
                {
                    "Name": "MODULE9_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 11,
                    "Value": true
                },
                {
                    "Name": "MODULE10_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 12,
                    "Value": true
                },
                {
                    "Name": "MODULE11_MODBUS_FAULT",
                    "Type": "ControllerFailure",
                    "BitPosition": 13,
                    "Value": true
                }
            ]
        }
    ]
}

=== openbmc/phosphor-modbus/rtu/profiles/PanasonicBJA3C0002ABatteryBackupUnit.json
{
    "DeviceType": "BatteryBackupUnit",
    "DeviceModel": "PanasonicBJA3C0002A",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x0",
        "Size": 8,
        "ExpectedValue": "Panasonic"
    },
    "InventoryRegisters": [
        {
            "Type": "Manufacturer",
            "Offset": "0x0",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x8",
            "Size": 8
        },
        {
            "Type": "BuildDate",
            "Offset": "0x10",
            "Size": 8
        },
        {
            "Type": "SparePartNumber",
            "Offset": "0x18",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x40",
            "Size": 16
        }
    ],
    "FirmwareRegisters": [
        {
            "Name": "BBU_FW_Revision",
            "Type": "Version",
            "Offset": "0x38",
            "Size": 4
        }
    ]
}
