=== openbmc/phosphor-modbus/rtu/schemas/device_profile.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ModbusRTUDeviceProfile",
    "type": "object",
    "required": [
        "DeviceType",
        "DeviceModel",
        "Parity",
        "BaudRate",
        "ProbeRegister"
    ],
    "additionalProperties": false,
    "properties": {
        "DeviceType": {
            "type": "string",
            "enum": [
                "BatteryBackupUnit",
                "CapacitorBankUnit",
                "FlowMeter",
                "HeatExchanger",
                "PowerMonitorModule",
                "PowerShelf",
                "PowerSupplyUnit",
                "ReservoirPumpUnit",
                "Valve"
            ]
        },
        "DeviceModel": {
            "type": "string",
            "enum": [
                "Artesyn7000552480000",
                "Artesyn7000552531000",
                "Artesyn7000555240000",
                "BelimoEV200ARXE",
                "Danfoss003Z8540",
                "DeltaBBUBC100AE000",
                "DeltaBBUBS723AE000",
                "DeltaBBUBU123AE000",
                "DeltaECD17020037",
                "DeltaECD27010006",
                "DeltaECD68000047",
                "DeltaECD68000049",
                "DeltaECD70000017",
                "DeltaECD70000020",
                "DeltaRDF040DSS5193E0",
                "PanasonicBJA3C0002A",
                "PanasonicBJBPM103A",
                "PanasonicBJBSB103A"
            ]
        },
        "Parity": {
            "type": "string",
            "enum": ["None", "Even", "Odd"]
        },
        "BaudRate": {
            "type": "integer"
        },
        "ProbeRegister": {
            "type": "object",
            "required": ["Offset", "Size", "ExpectedValue"],
            "additionalProperties": false,
            "properties": {
                "Offset": { "type": "string", "pattern": "^0x[0-9A-Fa-f]+$" },
                "Size": { "type": "integer" },
                "ExpectedValue": {
                    "oneOf": [{ "type": "integer" }, { "type": "string" }]
                }
            }
        },
        "InventoryRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Type": {
                        "type": "string",
                        "enum": [
                            "BuildDate",
                            "Manufacturer",
                            "Model",
                            "PartNumber",
                            "SerialNumber",
                            "SparePartNumber"
                        ]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Format": {
                        "type": "string",
                        "enum": ["String", "Integer"],
                        "default": "String"
                    }
                }
            }
        },
        "SensorRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size", "Format"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": [
                            "FanTach",
                            "LiquidFlow",
                            "Power",
                            "Pressure",
                            "Temperature",
                            "Voltage",
                            "Current",
                            "Airflow",
                            "Altitude",
                            "Energy",
                            "Frequency",
                            "Humidity",
                            "Utilization",
                            "Valve",
                            "Charge",
                            "RotationalPosition"
                        ]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Precision": { "type": "integer", "default": 0 },
                    "Scale": { "type": "number", "default": 1.0 },
                    "Shift": { "type": "number", "default": 0.0 },
                    "IsSigned": { "type": "boolean", "default": false },
                    "Format": {
                        "type": "string",
                        "enum": ["FixedPoint", "Float32", "Integer"]
                    }
                },
                "if": {
                    "properties": { "Format": { "const": "Float32" } }
                },
                "then": {
                    "properties": { "Size": { "const": 2 } }
                }
            }
        },
        "StatusRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Offset", "Bits"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Bits": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "Type",
                                "BitPosition",
                                "Value"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "Name": { "type": "string" },
                                "Type": {
                                    "type": "string",
                                    "enum": [
                                        "ControllerFailure",
                                        "FanFailure",
                                        "FilterFailure",
                                        "PowerFault",
                                        "PumpFailure",
                                        "LeakDetectedCritical",
                                        "LeakDetectedWarning",
                                        "SensorFailure",
                                        "SensorReadingCritical",
                                        "SensorReadingWarning"
                                    ]
                                },
                                "BitPosition": { "type": "integer" },
                                "Value": { "type": "boolean" }
                            }
                        }
                    }
                }
            }
        },
        "MetricRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size", "Format"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["ValveClosedDuration", "ValveOpenDuration"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Precision": { "type": "integer", "default": 0 },
                    "Scale": { "type": "number", "default": 1.0 },
                    "Shift": { "type": "number", "default": 0.0 },
                    "IsSigned": { "type": "boolean", "default": false },
                    "Format": {
                        "type": "string",
                        "enum": ["FixedPoint", "Float32", "Integer"]
                    }
                },
                "if": {
                    "properties": { "Format": { "const": "Float32" } }
                },
                "then": {
                    "properties": { "Size": { "const": 2 } }
                }
            }
        },
        "FirmwareRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["Version", "Update"]
                    },
                    "Format": {
                        "type": "string",
                        "enum": ["String", "Integer"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" }
                }
            }
        },
        "ConfigRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["UnixTime"]
                    },
                    "Offset": {
                        "type": "string",
                        "pattern": "^0x[0-9A-Fa-f]+$"
                    },
                    "Size": { "type": "integer" },
                    "Period": { "type": "integer" }
                }
            }
        }
    }
}

=== openbmc/phosphor-modbus/rtu/profiles/PanasonicBJBSB103APowerShelf.json
{
    "DeviceType": "PowerShelf",
    "DeviceModel": "PanasonicBJBSB103A",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x188",
        "Size": 8,
        "ExpectedValue": "Panasonic"
    },
    "InventoryRegisters": [
        {
            "Type": "Manufacturer",
            "Offset": "0x188",
            "Size": 8
        },
        {
            "Type": "SparePartNumber",
            "Offset": "0x190",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x198",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x1A8",
            "Size": 16
        },
        {
            "Type": "BuildDate",
            "Offset": "0x1B8",
            "Size": 8
        }
    ]
}

=== openbmc/phosphor-modbus/rtu/profiles/Artesyn7000552531000PowerShelf.json
{
    "DeviceType": "PowerShelf",
    "DeviceModel": "Artesyn7000552531000",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x188",
        "Size": 8,
        "ExpectedValue": "ARTESYN"
    },
    "InventoryRegisters": [
        {
            "Type": "Manufacturer",
            "Offset": "0x188",
            "Size": 8
        },
        {
            "Type": "SparePartNumber",
            "Offset": "0x190",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x198",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x1A8",
            "Size": 16
        },
        {
            "Type": "BuildDate",
            "Offset": "0x1B8",
            "Size": 8
        }
    ],
    "SensorRegisters": [
        {
            "Name": "PSU1_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x101",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU1_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x102",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU2_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x111",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU2_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x112",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU3_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x121",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU3_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x122",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU4_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x131",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU4_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x132",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU5_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x141",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU5_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x142",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU6_INPUT_AC_VOLT",
            "Type": "Voltage",
            "Offset": "0x151",
            "Size": 1,
            "Precision": 6,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        },
        {
            "Name": "PSU6_INPUT_AC_CURR",
            "Type": "Current",
            "Offset": "0x152",
            "Size": 1,
            "Precision": 10,
            "Scale": 1.0,
            "Shift": 0.0,
            "IsSigned": false,
            "Format": "FixedPoint"
        }
    ]
}

=== openbmc/phosphor-modbus/rtu/profiles/DeltaECD27010006CapacitorBankUnit.json
{
    "DeviceType": "CapacitorBankUnit",
    "DeviceModel": "DeltaECD27010006",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x0",
        "Size": 8,
        "ExpectedValue": "Delta"
    },
    "InventoryRegisters": [
        {
            "Type": "Manufacturer",
            "Offset": "0x0",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x8",
            "Size": 8
        },
        {
            "Type": "BuildDate",
            "Offset": "0x10",
            "Size": 8
        },
        {
            "Type": "SparePartNumber",
            "Offset": "0x18",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x40",
            "Size": 16
        }
    ],
    "FirmwareRegisters": [
        {
            "Name": "CBU_FW_Revision",
            "Type": "Version",
            "Offset": "0x38",
            "Size": 4
        }
    ],
    "SensorRegisters": [],
    "StatusRegisters": [
        {
            "Name": "STATUS",
            "Offset": "0x68",
            "Bits": [
                {
                    "Name": "DISCHARGE_NOT_ALLOWED",
                    "Type": "PowerFault",
                    "BitPosition": 15,
                    "Value": true
                },
                {
                    "Name": "CHARGE_NOT_ALLOWED",
                    "Type": "PowerFault",
                    "BitPosition": 14,
                    "Value": true
                },
                {
                    "Name": "TEMPERATURE_FAILURE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 13,
                    "Value": true
                },
                {
                    "Name": "PACK_OVER_CURRENT",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 12,
                    "Value": true
                },
                {
                    "Name": "CELL_UNDER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 11,
                    "Value": true
                },
                {
                    "Name": "PACK_UNDER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 10,
                    "Value": true
                },
                {
                    "Name": "CELL_OVER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 9,
                    "Value": true
                },
                {
                    "Name": "PACK_OVER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 8,
                    "Value": true
                },
                {
                    "Name": "EOL",
                    "Type": "ControllerFailure",
                    "BitPosition": 7,
                    "Value": true
                },
                {
                    "Name": "FAN_FAILURE",
                    "Type": "FanFailure",
                    "BitPosition": 6,
                    "Value": true
                },
                {
                    "Name": "CELL_BALANCING_FAILURE",
                    "Type": "ControllerFailure",
                    "BitPosition": 5,
                    "Value": true
                }
            ]
        },
        {
            "Name": "STATUS_WORD",
            "Offset": "0x99",
            "Bits": [
                {
                    "Name": "FAN_3_FAULT",
                    "Type": "FanFailure",
                    "BitPosition": 5,
                    "Value": true
                },
                {
                    "Name": "FAN_2_FAULT",
                    "Type": "FanFailure",
                    "BitPosition": 4,
                    "Value": true
                },
                {
                    "Name": "FAN_1_FAULT",
                    "Type": "FanFailure",
                    "BitPosition": 3,
                    "Value": true
                },
                {
                    "Name": "BUCK_MODE_FAULT",
                    "Type": "PowerFault",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "BOOST_MODE_FAULT",
                    "Type": "PowerFault",
                    "BitPosition": 1,
                    "Value": true
                },
                {
                    "Name": "TEMPERATURE_FAULT",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 0,
                    "Value": true
                }
            ]
        },
        {
            "Name": "STATUS_POWER_CHARGER",
            "Offset": "0x9A",
            "Bits": [
                {
                    "Name": "DISCHARGE_INPUT_UNDER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 4,
                    "Value": true
                },
                {
                    "Name": "DISCHARGE_OUTPUT_OVER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "DISCHARGE_OUTPUT_OVER_CURRENT",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 1,
                    "Value": true
                }
            ]
        },
        {
            "Name": "STATUS_POWER_DISCHARGER",
            "Offset": "0x9B",
            "Bits": [
                {
                    "Name": "CHARGE_OUTPUT_OVER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 3,
                    "Value": true
                },
                {
                    "Name": "CHARGE_INPUT_UNDER_VOLTAGE",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "CHARGE_OUTPUT_OVER_CURRENT",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 0,
                    "Value": true
                }
            ]
        },
        {
            "Name": "STATUS_TEMP",
            "Offset": "0x9D",
            "Bits": [
                {
                    "Name": "SUPERCAP_PACK_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 4,
                    "Value": true
                },
                {
                    "Name": "DCDC_MODULE2_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 3,
                    "Value": true
                },
                {
                    "Name": "DCDC_MODULE1_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "OUTPUT_AMBIENT_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 1,
                    "Value": true
                },
                {
                    "Name": "BUSBAR_CLIP_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 5,
                    "Value": true
                },
                {
                    "Name": "INPUT_AMBIENT_OVER_TEMP",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 0,
                    "Value": true
                }
            ]
        },
        {
            "Name": "HW_SIGNAL",
            "Offset": "0xA4",
            "Bits": [
                {
                    "Name": "AC_LOSS_DETECTED",
                    "Type": "PowerFault",
                    "BitPosition": 10,
                    "Value": true
                },
                {
                    "Name": "DAISY_CHAIN_FAILURE",
                    "Type": "ControllerFailure",
                    "BitPosition": 8,
                    "Value": true
                },
                {
                    "Name": "ISHARE_CABLE_NOT_DETECTED",
                    "Type": "ControllerFailure",
                    "BitPosition": 0,
                    "Value": true
                }
            ]
        }
    ],
    "ConfigRegisters": [
        {
            "Name": "SyncTime",
            "Type": "UnixTime",
            "Offset": "0x65",
            "Size": 2,
            "Period": 3600
        }
    ]
}

=== openbmc/phosphor-modbus/rtu/profiles/DeltaECD17020037PowerSupplyUnit.json
{
    "DeviceType": "PowerSupplyUnit",
    "DeviceModel": "DeltaECD17020037",
    "Parity": "Even",
    "BaudRate": 115200,
    "ProbeRegister": {
        "Offset": "0x8",
        "Size": 8,
        "ExpectedValue": "ECD17020037"
    },
    "InventoryRegisters": [
        {
            "Type": "SparePartNumber",
            "Offset": "0x0",
            "Size": 8
        },
        {
            "Type": "Model",
            "Offset": "0x8",
            "Size": 8
        },
        {
            "Type": "BuildDate",
            "Offset": "0x10",
            "Size": 8
        },
        {
            "Type": "SerialNumber",
            "Offset": "0x18",
            "Size": 16
        }
    ],
    "FirmwareRegisters": [
        {
            "Name": "PSU_FW_Revision",
            "Type": "Version",
            "Offset": "0x30",
            "Size": 4
        }
    ]
}
