=== openbmc/phosphor-modbus/schemas/device_profile.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ModbusRTUDeviceProfile",
    "type": "object",
    "required": [
        "DeviceType",
        "DeviceModel",
        "Parity",
        "BaudRate",
        "ProbeRegister"
    ],
    "additionalProperties": false,
    "properties": {
        "DeviceType": {
            "type": "string",
            "enum": [
                "BatteryBackupUnit",
                "CapacitorBankUnit",
                "FlowMeter",
                "HeatExchanger",
                "PowerMonitorModule",
                "PowerSupplyUnit",
                "ReservoirPumpUnit",
                "Valve"
            ]
        },
        "DeviceModel": {
            "type": "string",
            "enum": [
                "Artesyn7000433970000",
                "Danfoss003Z8540",
                "DeltaECD70000020",
                "DeltaRDF040DSS5193E0",
                "PanasonicBJBPM102A0001"
            ]
        },
        "Parity": {
            "type": "string",
            "enum": ["None", "Even", "Odd"]
        },
        "BaudRate": {
            "type": "integer"
        },
        "ProbeRegister": {
            "type": "object",
            "required": ["Offset", "Size", "ExpectedValue"],
            "additionalProperties": false,
            "properties": {
                "Offset": { "type": "integer" },
                "Size": { "type": "integer" },
                "ExpectedValue": {
                    "oneOf": [{ "type": "integer" }, { "type": "string" }]
                }
            }
        },
        "InventoryRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Type": {
                        "type": "string",
                        "enum": [
                            "BuildDate",
                            "Manufacturer",
                            "Model",
                            "PartNumber",
                            "SerialNumber",
                            "SparePartNumber"
                        ]
                    },
                    "Offset": { "type": "integer" },
                    "Size": { "type": "integer" }
                }
            }
        },
        "SensorRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size", "Format"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": [
                            "FanTach",
                            "LiquidFlow",
                            "Power",
                            "Pressure",
                            "Temperature",
                            "Voltage",
                            "Current",
                            "Airflow",
                            "Altitude",
                            "Energy",
                            "Frequency",
                            "Humidity",
                            "Utilization",
                            "Valve"
                        ]
                    },
                    "Offset": { "type": "integer" },
                    "Size": { "type": "integer" },
                    "Precision": { "type": "integer", "default": 0 },
                    "Scale": { "type": "number", "default": 1.0 },
                    "Shift": { "type": "number", "default": 0.0 },
                    "IsSigned": { "type": "boolean", "default": false },
                    "Format": {
                        "type": "string",
                        "enum": ["FloatingPoint", "Integer"]
                    }
                }
            }
        },
        "StatusRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Offset", "Bits"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Offset": { "type": "integer" },
                    "Bits": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "Type",
                                "BitPosition",
                                "Value"
                            ],
                            "additionalProperties": false,
                            "properties": {
                                "Name": { "type": "string" },
                                "Type": {
                                    "type": "string",
                                    "enum": [
                                        "ControllerFailure",
                                        "FanFailure",
                                        "FilterFailure",
                                        "PowerFault",
                                        "PumpFailure",
                                        "LeakDetectedCritical",
                                        "LeakDetectedWarning",
                                        "SensorFailure",
                                        "SensorReadingCritical",
                                        "SensorReadingWarning"
                                    ]
                                },
                                "BitPosition": { "type": "integer" },
                                "Value": { "type": "boolean" }
                            }
                        }
                    }
                }
            }
        },
        "FirmwareRegisters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["Name", "Type", "Offset", "Size"],
                "additionalProperties": false,
                "properties": {
                    "Name": { "type": "string" },
                    "Type": {
                        "type": "string",
                        "enum": ["Version", "Update"]
                    },
                    "Offset": { "type": "integer" },
                    "Size": { "type": "integer" }
                }
            }
        }
    }
}

=== openbmc/phosphor-modbus/rtu/profiles/DeltaRDF040DSS5193E0ReservoirPumpUnit.json
{
    "DeviceType": "ReservoirPumpUnit",
    "DeviceModel": "DeltaRDF040DSS5193E0",
    "Parity": "None",
    "BaudRate": 19200,
    "ProbeRegister": {
        "Offset": 6604,
        "Size": 8,
        "ExpectedValue": "RDF040DSS5193E0"
    },
    "InventoryRegisters": [
        {
            "Type": "Model",
            "Offset": 6604,
            "Size": 8
        },
        {
            "Type": "BuildDate",
            "Offset": 6612,
            "Size": 4
        },
        {
            "Type": "SerialNumber",
            "Offset": 6616,
            "Size": 8
        },
        {
            "Type": "SparePartNumber",
            "Offset": 6652,
            "Size": 4
        }
    ],
    "SensorRegisters": [
        {
            "Name": "RPU_Coolant_Inlet_Temp_C",
            "Type": "Temperature",
            "Offset": 36866,
            "Size": 1,
            "Precision": 0,
            "Scale": 0.1,
            "Shift": 0.0,
            "IsSigned": true,
            "Format": "FloatingPoint"
        },
        {
            "Name": "RPU_Coolant_Outlet_Temp_C",
            "Type": "Temperature",
            "Offset": 36865,
            "Size": 1,
            "Precision": 0,
            "Scale": 0.1,
            "Shift": 0.0,
            "IsSigned": true,
            "Format": "FloatingPoint"
        }
    ],
    "StatusRegisters": [
        {
            "Offset": 37377,
            "Bits": [
                {
                    "Name": "RPU_Coolant_Inlet_Temp_C",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 2,
                    "Value": true
                },
                {
                    "Name": "RPU_Coolant_Outlet_Temp_C",
                    "Type": "SensorReadingCritical",
                    "BitPosition": 1,
                    "Value": true
                }
            ]
        },
        {
            "Offset": 37376,
            "Bits": [
                {
                    "Name": "RPU_Coolant_Inlet_Temp_C",
                    "Type": "SensorFailure",
                    "BitPosition": 0,
                    "Value": true
                },
                {
                    "Name": "RPU_Coolant_Outlet_Temp_C",
                    "Type": "SensorFailure",
                    "BitPosition": 1,
                    "Value": true
                }
            ]
        }
    ],
    "FirmwareRegisters": [
        {
            "Name": "RPU_PLC_FW_Revision",
            "Type": "Version",
            "Offset": 6632,
            "Size": 4
        }
    ]
}
